services: docker
before_install:
  - docker -v
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  # Seed database
  - docker build -t "bkuhl/attendance-randomizer:latest" -f "infrastructure/Dockerfile" .
after_success:
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then docker push "bkuhl/attendance-randomizer:latest" ; fi